
PPU_CTRL        = $2000
PPU_MASK        = $2001
PPU_STATUS      = $2002
PPU_OAMADDR     = $2003
PPU_OAMDATA     = $2004
PPU_SCROLL      = $2005
PPU_ADDR        = $2006
PPU_DATA        = $2007

APU_PULSE1      = $4000
APU_PULSE2      = $4004
APU_TRI         = $4008
APU_NOISE       = $400C
DMC_FREQ        = $4010
DMC_RAW         = $4011
DMC_START       = $4012
DMC_LEN         = $4013
OAM_DMA         = $4014
APU_STATUS      = $4015
JOY1            = $4016
JOY2            = $4017
