;------------------------------------------------------------------------------
;	FAMILY BASIC V3 symbols & address
;
;	This is extracted from the deliverables of the following project.
;		https://github.com/micahcowan/fbdasm
;		https://famibe.addictivecode.org/disassembly/fb3.nes.html
;
;------------------------------------------------------------------------------

GOTO		=	$96C6
GOSUB		=	$9648
RUN		=	$86B0
RETURN		=	$96A6
RESTORE		=	$9EC9
ErrorSyntax	=	$8491
LIST		=	$8767
SYSTEM_BACKUP	=	$818F
SPRITE		=	$AFFC
PRINT		=	$88C5
FOR		=	$97FC
NEXT		=	$9887
PAUSE		=	$9716
INPUT		=	$993C
LINPUT		=	$9A6C
DATA_REM	=	$8467
IF		=	$9782
READ		=	$9F36
DIM		=	$9C0C
STOP		=	$885B
CONT		=	$889C
LAE0A		=	$AE0A
CLEAR		=	$97A4
ON		=	$9AFD
CUT		=	$CBDC
NEW		=	$84B6
POKE		=	$975D
CGSET		=	$AF4F
VIEW		=	$B153
MOVE		=	$CBB3
END		=	$826A
PLAY		=	$A01E
BEEP		=	$BCD0
LOAD		=	$9DE1
SAVE		=	$9D64
POSITON		=	$CB9B
KEY		=	$9B68
COLOR		=	$C4CA
DEF		=	$B098
CGEN		=	$AED1
SWAP		=	$9A0E
CALL		=	$970A
LOCATE		=	$9748
PALET		=	$AEF3
ERA		=	$CBD9
TR		=	$962B
FIND		=	$9573
GAME		=	$AD5B
BGTOOL		=	$BFD1
AUTO		=	$8BDA
DELETE		=	$8758
RENUM		=	$8C30
FILTER		=	$AEB8
CLICK		=	$9625
SCREEN		=	$AE48
ERROR_		=	$9510
RESUME		=	$9527
BGPUT		=	$B201
BGGET		=	$B1B8
CAN		=	$CC6C

FnABS		=	$A984
FnASC		=	$AA28
FnSTR_STR	=	$AAA6
FnFRE		=	$A91F
FnLEN		=	$AA1D
FnPEEK		=	$A973
FnRND		=	$A9BD
FnSGN		=	$A99C
FnMID_STR	=	$AC81
FnSTICK		=	$AD38
FnSTRIG		=	$AD47
FnXPOS		=	$A958
FnYPOS		=	$A961
FnVAL		=	$AADF
FnPOS		=	$A933
FnCSRLIN	=	$A8E6
FnCHR_STR	=	$AA82
FnHEX_STR	=	$AAD6
FnINKEY_STR	=	$AB58
FnRIGHT_STR	=	$AC41
FnLEFT_STR	=	$ABED
FnSCR_STR	=	$AA3B
FnINSTR		=	$ABAF
FnCRASH		=	$CC04
FnERR		=	$A90D
FnERL		=	$A914
FnVCT		=	$A96A
